#!/bin/bash

# ─────────────────────────────────────────────────────────────────
#  install.sh - Installs TaskTrackerCLI on your system
#
#  WHAT THIS SCRIPT DOES:
#  1. Checks that Java is installed
#  2. Compiles the Java source files
#  3. Creates a "taskcli" command you can run from anywhere
#
#  HOW TO USE:
#    chmod +x install.sh
#    ./install.sh
# ─────────────────────────────────────────────────────────────────

# Colors for pretty output
GREEN="\e[32m"
RED="\e[31m"
YELLOW="\e[33m"
RESET="\e[0m"

info()    { echo -e "${GREEN}[✔]${RESET} $1"; }
warning() { echo -e "${YELLOW}[!]${RESET} $1"; }
error()   { echo -e "${RED}[✘]${RESET} $1"; exit 1; }

# ─────────────────────────────────────────────────────────────────
#  STEP 1: Get the project root folder
# ─────────────────────────────────────────────────────────────────
INSTALL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo ""
echo "================================================"
echo "   TaskTrackerCLI Installer"
echo "================================================"
echo ""

# ─────────────────────────────────────────────────────────────────
#  STEP 2: Check Java is installed
# ─────────────────────────────────────────────────────────────────
info "Checking for Java..."

if ! command -v java &> /dev/null; then
    error "Java not found. Install it:
       Ubuntu/Debian → sudo apt install default-jdk
       Mac           → brew install openjdk"
fi

if ! command -v javac &> /dev/null; then
    error "javac not found. Install JDK:
       Ubuntu/Debian → sudo apt install default-jdk
       Mac           → brew install openjdk"
fi

JAVA_VERSION=$(java -version 2>&1 | head -1)
info "Found: $JAVA_VERSION"

# ─────────────────────────────────────────────────────────────────
#  STEP 3: Check source files exist
# ─────────────────────────────────────────────────────────────────
info "Checking source files..."

if [ ! -d "$INSTALL_DIR/src" ]; then
    error "src not found. Run this script from the project root."
fi

for f in "taskCli.java" "task.java" "taskManager.java" "jsonStore.java"; do
    if [ ! -f "$INSTALL_DIR/src$f" ]; then
        error "Missing: src $f"
    fi
done

info "All source files found."

# ─────────────────────────────────────────────────────────────────
#  STEP 4: Compile
# ─────────────────────────────────────────────────────────────────
info "Compiling Java files..."

mkdir -p "$INSTALL_DIR/bin"
javac -d "$INSTALL_DIR/bin" "$INSTALL_DIR/src"*.java

if [ $? -ne 0 ]; then
    error "Compilation failed. Fix the errors above and try again."
fi

info "Compilation successful."

# ─────────────────────────────────────────────────────────────────
#  STEP 5: Create the wrapper script
#  We hardcode the bin path so it works from anywhere
# ─────────────────────────────────────────────────────────────────
info "Creating taskcli wrapper..."

WRAPPER="$INSTALL_DIR/taskcli"
BIN_PATH="$INSTALL_DIR/bin"

cat > "$WRAPPER" << WEOF
#!/bin/bash
# taskcli - auto-generated by install.sh

if ! command -v java &> /dev/null; then
    echo "Error: Java is not installed."
    exit 1
fi

if [ \$# -eq 0 ]; then
    java -cp "$BIN_PATH" package1.taskCli
    exit 0
fi

java -cp "$BIN_PATH" package1.taskCli "\$@"
WEOF

chmod +x "$WRAPPER"
info "Wrapper created."

# ─────────────────────────────────────────────────────────────────
#  STEP 6: Install globally
# ─────────────────────────────────────────────────────────────────
info "Installing to /usr/local/bin..."

if sudo cp "$WRAPPER" /usr/local/bin/taskcli 2>/dev/null; then
    sudo chmod +x /usr/local/bin/taskcli
    info "Installed globally."
else
    warning "Could not install globally (no sudo?)"
    warning "Run locally instead: ./taskcli"
fi

# ─────────────────────────────────────────────────────────────────
#  DONE
# ─────────────────────────────────────────────────────────────────
echo ""
echo "================================================"
info "Installation complete!"
echo "================================================"
echo ""
echo "  Try it:"
echo "    taskcli add \"Buy groceries\""
echo "    taskcli list"
echo "    taskcli mark-done 1"
echo ""
echo "  Uninstall anytime:"
echo "    sudo rm /usr/local/bin/taskcli"
echo ""
